[package]
name = "fluxer-neptunium"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
fluxer-gateway = { path = "../fluxer-gateway" }
rand = "0.10.0"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"

[lints.clippy]
pedantic = "warn"
